name: ThermoSurvival
version: 1.0
main: com.parlamentum.thermosurvival.ThermoSurvivalPlugin
api-version: 1.20
author: parlamentum
description: A lightweight temperature system.
permissions:
  thermosurvival.bypass:
    description: Bypass temperature effects
    default: op

